from __future__ import annotations

from typing import Any

from playwright.sync_api import sync_playwright

from expensify_scraper.auth import (
    DEFAULT_RECEIPT_HEADERS,
    AuthError,
    AuthSession,
    PlaywrightReceiptResponse,
    response_looks_like_receipt,
    save_session,
)
from expensify_scraper.classic_api import (
    ClassicAPIError,
    fetch_transactions,
    mint_classic_tokens,
)
from expensify_scraper.config import Settings

ONYX_SESSION_JS = """
async () => {
  const openDb = (name) => new Promise((resolve, reject) => {
    const req = indexedDB.open(name);
    req.onerror = () => reject(String(req.error));
    req.onsuccess = () => resolve(req.result);
  });
  const db = await openDb('OnyxDB');
  const tx = db.transaction('keyvaluepairs', 'readonly');
  const store = tx.objectStore('keyvaluepairs');
  const session = await new Promise((resolve, reject) => {
    const req = store.get('session');
    req.onsuccess = () => resolve(req.result || {});
    req.onerror = () => reject(req.error);
  });
  db.close();
  return {
    authToken: session.authToken || '',
    encryptedAuthToken: session.encryptedAuthToken || ''
  };
}
"""


ONYX_CREDENTIALS_JS = """
async () => {
  const openDb = (name) => new Promise((resolve, reject) => {
    const req = indexedDB.open(name);
    req.onerror = () => reject(String(req.error));
    req.onsuccess = () => resolve(req.result);
  });
  const db = await openDb('OnyxDB');
  const tx = db.transaction('keyvaluepairs', 'readonly');
  const store = tx.objectStore('keyvaluepairs');
  const creds = await new Promise((resolve, reject) => {
    const req = store.get('credentials');
    req.onsuccess = () => resolve(req.result || {});
    req.onerror = () => reject(req.error);
  });
  db.close();
  return {
    autoGeneratedLogin: creds.autoGeneratedLogin || '',
    autoGeneratedPassword: creds.autoGeneratedPassword || ''
  };
}
"""


def extract_onyx_session(page: Any) -> tuple[str, str]:
    try:
        data = page.evaluate(ONYX_SESSION_JS)
    except Exception:
        return "", ""
    return str(data.get("authToken") or ""), str(data.get("encryptedAuthToken") or "")


def extract_onyx_credentials(page: Any) -> tuple[str, str]:
    try:
        data = page.evaluate(ONYX_CREDENTIALS_JS)
    except Exception:
        return "", ""
    return str(data.get("autoGeneratedLogin") or ""), str(
        data.get("autoGeneratedPassword") or ""
    )


def mint_classic_auth_token(login: str, password: str) -> str:
    """Mint a Classic-compatible authToken from New Expensify generated credentials."""
    try:
        return mint_classic_tokens(login, password).auth_token
    except ClassicAPIError:
        return ""


def refresh_session_tokens(settings: Settings, session: AuthSession) -> AuthSession:
    """Reuse a stored token or mint a new one from the saved browser login."""
    if session.auth_token:
        try:
            fetch_transactions(session.auth_token)
            return session
        except ClassicAPIError:
            pass
    if not settings.storage_state_path.exists():
        raise AuthError("No saved browser session. Run: expensify-scraper auth")

    with sync_playwright() as playwright:
        browser = playwright.chromium.launch(headless=True)
        context = browser.new_context(storage_state=str(settings.storage_state_path))
        page = context.new_page()
        page.goto(
            f"{settings.new_expensify_url}/home",
            wait_until="domcontentloaded",
            timeout=60_000,
        )
        page.wait_for_timeout(2000)
        login, password = extract_onyx_credentials(page)
        browser.close()

    tokens = mint_classic_tokens(login, password)
    session.auth_token = tokens.auth_token
    session.encrypted_auth_token = tokens.encrypted_auth_token
    save_session(settings, session)
    return session


class ReceiptBrowser:
    """Logged-in Chromium context used to download receipt files."""

    def __init__(self, settings: Settings, session: AuthSession) -> None:
        self.settings = settings
        self.session = session
        self._playwright = None
        self._browser = None
        self._context = None
        self._page = None

    def __enter__(self) -> ReceiptBrowser:
        if not self.settings.storage_state_path.exists():
            raise RuntimeError("No saved browser session. Run: expensify-scraper auth")
        self._playwright = sync_playwright().start()
        self._browser = self._playwright.chromium.launch(headless=True)
        self._context = self._browser.new_context(
            storage_state=str(self.settings.storage_state_path),
            extra_http_headers=DEFAULT_RECEIPT_HEADERS,
        )
        self._page = self._context.new_page()
        self._page.goto(
            f"{self.settings.new_expensify_url}/home",
            wait_until="domcontentloaded",
            timeout=60_000,
        )
        self._page.wait_for_timeout(2000)
        auth_token, encrypted = extract_onyx_session(self._page)
        if auth_token:
            self.session.auth_token = auth_token
        if encrypted:
            self.session.encrypted_auth_token = encrypted
        login, password = extract_onyx_credentials(self._page)
        try:
            tokens = mint_classic_tokens(login, password)
            self.session.auth_token = tokens.auth_token
            if tokens.encrypted_auth_token:
                self.session.encrypted_auth_token = tokens.encrypted_auth_token
        except ClassicAPIError:
            pass
        if self.session.auth_token:
            self._context.add_cookies(
                [
                    {
                        "name": "authToken",
                        "value": self.session.auth_token,
                        "domain": ".expensify.com",
                        "path": "/",
                    }
                ]
            )
        return self

    def __exit__(self, *args: object) -> None:
        if self._browser:
            self._browser.close()
        if self._playwright:
            self._playwright.stop()

    def fetch(self, url: str) -> PlaywrightReceiptResponse:
        assert self._page is not None
        encrypted = self.session.encrypted_auth_token
        auth_token = self.session.auth_token
        attempts: list[tuple[str, dict[str, str]]] = [(url, {})]
        if encrypted:
            attempts.append((url, {"X-Chat-Attachment-Token": encrypted}))
        if auth_token:
            attempts.append((url, {"X-Chat-Attachment-Token": auth_token}))

        last = PlaywrightReceiptResponse(0, {}, b"")
        for final_url, extra_headers in attempts:
            response = self._page.request.get(
                final_url,
                headers=extra_headers,
                timeout=120_000,
            )
            last = PlaywrightReceiptResponse(
                response.status,
                {key: value for key, value in response.headers.items()},
                response.body(),
            )
            if response_looks_like_receipt(last):
                return last
        return last
